version: "3"
services:
  records:
    image: docker.io/cybervagabond/csv_parser
    container_name: csv_parser
    depends_on:
      - db
      -
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=records
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data