version: "3"
services:
  records:


  db:
    image: postgres:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=records
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data